/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package principal;

/**
 *
 * @author carlos
 */
import clientes.*;
import javax.swing.JFrame;
import pecas.*;
import servicos.*;
import sobre.*;
import vendas.*;
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        barraDeMenu = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        novoCliente = new javax.swing.JMenuItem();
        gerClientes = new javax.swing.JMenuItem();
        menuPecas = new javax.swing.JMenu();
        novaPeca = new javax.swing.JMenuItem();
        gerPecas = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        novaVenda = new javax.swing.JMenuItem();
        regVendas = new javax.swing.JMenuItem();
        menuServico = new javax.swing.JMenu();
        novoServicos = new javax.swing.JMenuItem();
        realizaServ = new javax.swing.JMenuItem();
        gerenciaServ = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shalon BA - Tela Inicial");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoShalonPB.png"))); // NOI18N
        jLabel1.setEnabled(false);

        menuClientes.setText("Clientes");

        novoCliente.setText("Novo");
        novoCliente.setToolTipText("Adicione novos clientes ao banco de dados");
        novoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteActionPerformed(evt);
            }
        });
        menuClientes.add(novoCliente);

        gerClientes.setText("Gerenciar");
        gerClientes.setToolTipText("Consulte, edite ou exclua registros de clientes");
        gerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerClientesActionPerformed(evt);
            }
        });
        menuClientes.add(gerClientes);

        barraDeMenu.add(menuClientes);

        menuPecas.setText("Peças");

        novaPeca.setText("Novo");
        novaPeca.setToolTipText("Cadastre novas peças do estoque");
        novaPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaPecaActionPerformed(evt);
            }
        });
        menuPecas.add(novaPeca);

        gerPecas.setText("Gerenciar Estoque");
        gerPecas.setToolTipText("Pesquise, edite ou exclua registros de peças");
        gerPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerPecasActionPerformed(evt);
            }
        });
        menuPecas.add(gerPecas);

        barraDeMenu.add(menuPecas);

        menuVendas.setText("Vendas");

        novaVenda.setText("Nova Venda");
        novaVenda.setToolTipText("Realize uma venda");
        novaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaVendaActionPerformed(evt);
            }
        });
        menuVendas.add(novaVenda);

        regVendas.setText("Registro");
        regVendas.setToolTipText("Consulte o registro de vendas já feitas");
        menuVendas.add(regVendas);

        barraDeMenu.add(menuVendas);

        menuServico.setText("Serviços");

        novoServicos.setText("Novo Serviço");
        novoServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoServicosActionPerformed(evt);
            }
        });
        menuServico.add(novoServicos);

        realizaServ.setText("Realizar Serviço");
        realizaServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizaServActionPerformed(evt);
            }
        });
        menuServico.add(realizaServ);

        gerenciaServ.setText("Gerenciar Serviços");
        gerenciaServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciaServActionPerformed(evt);
            }
        });
        menuServico.add(gerenciaServ);

        barraDeMenu.add(menuServico);

        jMenu1.setText("Sobre");

        jMenuItem1.setText("Shopware");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        barraDeMenu.add(jMenu1);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void exibeTela(JFrame tela){
    tela.setVisible(true);
    tela.setLocationRelativeTo(null);
}
    private void novoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteActionPerformed
        NCliente novo = new NCliente();
        exibeTela(novo);
    }//GEN-LAST:event_novoClienteActionPerformed

    private void gerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerClientesActionPerformed
        GClientes gc = new GClientes();
        exibeTela(gc);
    }//GEN-LAST:event_gerClientesActionPerformed

    private void novaPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaPecaActionPerformed
        NPeca np = new NPeca();
        exibeTela(np);
    }//GEN-LAST:event_novaPecaActionPerformed

    private void gerPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerPecasActionPerformed
        GPecas gp = new GPecas();
        exibeTela(gp);
    }//GEN-LAST:event_gerPecasActionPerformed

    private void novaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaVendaActionPerformed
         NVenda nv = new NVenda();
         exibeTela(nv);
    }//GEN-LAST:event_novaVendaActionPerformed

    private void novoServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoServicosActionPerformed
        NServico ns=new NServico();
        exibeTela(ns);
    }//GEN-LAST:event_novoServicosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void realizaServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizaServActionPerformed
        RealizaServico realizaS=new RealizaServico();
        exibeTela(realizaS);
    }//GEN-LAST:event_realizaServActionPerformed

    private void gerenciaServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciaServActionPerformed
        GServicos gerenciaS=new GServicos();
        exibeTela(gerenciaS);
    }//GEN-LAST:event_gerenciaServActionPerformed

    
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem gerClientes;
    private javax.swing.JMenuItem gerPecas;
    private javax.swing.JMenuItem gerenciaServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuPecas;
    private javax.swing.JMenu menuServico;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenuItem novaPeca;
    private javax.swing.JMenuItem novaVenda;
    private javax.swing.JMenuItem novoCliente;
    private javax.swing.JMenuItem novoServicos;
    private javax.swing.JMenuItem realizaServ;
    private javax.swing.JMenuItem regVendas;
    // End of variables declaration//GEN-END:variables
}
