/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clientes;

/**
 *
 * @author carlos
 */
public class GClientes extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisar
     */
    public GClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        opNomeGC = new javax.swing.JRadioButton();
        opEmailGC = new javax.swing.JRadioButton();
        opIdGC = new javax.swing.JRadioButton();
        textoGC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultGC = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        detGC = new javax.swing.JButton();
        editaClienteGC = new javax.swing.JButton();
        delGC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        voltaGC = new javax.swing.JButton();
        pesquisaGC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Clientes");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Gerenciar Clientes");

        jLabel2.setText("Pesquisar por:");

        opNomeGC.setText("Nome");
        opNomeGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opNomeGCActionPerformed(evt);
            }
        });

        opEmailGC.setText("Email");
        opEmailGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEmailGCActionPerformed(evt);
            }
        });

        opIdGC.setText("ID");
        opIdGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIdGCActionPerformed(evt);
            }
        });

        textoGC.setEditable(false);
        textoGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoGCActionPerformed(evt);
            }
        });

        resultGC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultGC.setMinimumSize(new java.awt.Dimension(30, 139));
        resultGC.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(resultGC);
        if (resultGC.getColumnModel().getColumnCount() > 0) {
            resultGC.getColumnModel().getColumn(0).setResizable(false);
            resultGC.getColumnModel().getColumn(0).setPreferredWidth(5);
            resultGC.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel3.setText("Resultados:");

        detGC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/detalhes.png"))); // NOI18N
        detGC.setMaximumSize(new java.awt.Dimension(90, 23));
        detGC.setMinimumSize(new java.awt.Dimension(90, 23));
        detGC.setToolTipText("Detalhes");
        detGC.setPreferredSize(new java.awt.Dimension(90, 23));

        editaClienteGC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editar.png"))); // NOI18N
        editaClienteGC.setMaximumSize(new java.awt.Dimension(90, 23));
        editaClienteGC.setMinimumSize(new java.awt.Dimension(90, 23));
        editaClienteGC.setToolTipText("Editar");
        editaClienteGC.setPreferredSize(new java.awt.Dimension(90, 23));
        editaClienteGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaClienteGCActionPerformed(evt);
            }
        });

        delGC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Recycle-Closed.png"))); // NOI18N
        delGC.setMaximumSize(new java.awt.Dimension(90, 23));
        delGC.setMinimumSize(new java.awt.Dimension(90, 23));
        delGC.setPreferredSize(new java.awt.Dimension(90, 23));
        delGC.setToolTipText("Deletar Cliente");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoShalonSmall2.png"))); // NOI18N

        voltaGC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1433560560_reply.png"))); // NOI18N
        voltaGC.setToolTipText("Voltar");
        voltaGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaGCActionPerformed(evt);
            }
        });

        pesquisaGC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pesquisa.png"))); // NOI18N
        pesquisaGC.setToolTipText("Pesquisar");
        pesquisaGC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaGCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opIdGC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opNomeGC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opEmailGC))
                    .addComponent(textoGC)
                    .addComponent(pesquisaGC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltaGC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editaClienteGC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detGC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delGC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(opIdGC)
                    .addComponent(opNomeGC)
                    .addComponent(opEmailGC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisaGC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(detGC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editaClienteGC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delGC, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(voltaGC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opNomeGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opNomeGCActionPerformed
        if(opNomeGC.isSelected()){
            opEmailGC.setSelected(false);
            opIdGC.setSelected(false);
            textoGC.setEditable(true);
        }
        else{
            textoGC.setEditable(false);
        }
    }//GEN-LAST:event_opNomeGCActionPerformed

    private void opIdGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIdGCActionPerformed
        if(opIdGC.isSelected()){
            opEmailGC.setSelected(false);
            opNomeGC.setSelected(false);
            textoGC.setEditable(true);
        }
        else{
            textoGC.setEditable(false);
        }
    }//GEN-LAST:event_opIdGCActionPerformed

    private void opEmailGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEmailGCActionPerformed
        if(opEmailGC.isSelected()){
            opNomeGC.setSelected(false);
            opIdGC.setSelected(false);
            textoGC.setEditable(true);
        }
        else{
            textoGC.setEditable(false);
        }
    }//GEN-LAST:event_opEmailGCActionPerformed

    private void textoGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoGCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoGCActionPerformed

    private void voltaGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaGCActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltaGCActionPerformed

    private void editaClienteGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaClienteGCActionPerformed
        ECliente ec=new ECliente();
        System.err.println(textoGC.getText());
        
        ec.setVisible(true);
        ec.setLocationRelativeTo(null);
    }//GEN-LAST:event_editaClienteGCActionPerformed

    private void pesquisaGCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaGCActionPerformed
        
    }//GEN-LAST:event_pesquisaGCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delGC;
    private javax.swing.JButton detGC;
    private javax.swing.JButton editaClienteGC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton opEmailGC;
    private javax.swing.JRadioButton opIdGC;
    private javax.swing.JRadioButton opNomeGC;
    private javax.swing.JButton pesquisaGC;
    private javax.swing.JTable resultGC;
    private javax.swing.JTextField textoGC;
    private javax.swing.JButton voltaGC;
    // End of variables declaration//GEN-END:variables
}
